More cli tests
terser/html-minifier-terser pull request #95
Opened 2021-11-13 11:19 UTC by sibiraj-s

- add tests for some common cases
- prefer native mkdir recursion to manual recursion

2021-11-14 19:26 UTC, DanielRuf requested changes

2021-11-14 19:26 UTC, DanielRuf commented on tests/cli.spec.js
> +  // TODO: Temp fix for CI running on node 12, since
```suggestion
  // TODO: Temp fix for CI running on node 12
```

2021-11-14 19:26 UTC, DanielRuf commented on tests/cli.spec.js
> +  // since fs.rm is available only since node 14
```suggestion
  // because fs.rm is available only in node 14 and newer
```

2021-11-14 19:26 UTC, DanielRuf commented on tests/fixtures/url.html
> +  <form action="http://website.com/folder/folder2/index.html">
```suggestion
  <form action="http://example.com/folder/folder2/index.html">
```

2021-11-14 19:26 UTC, DanielRuf commented on tests/fixtures/url.html
> +  <link rel="stylesheet" href="http://website.com/style.css">
```suggestion
  <link rel="stylesheet" href="http://example.com/style.css">
```

2021-11-14 19:26 UTC, DanielRuf commented on tests/fixtures/url.html
> +    <a href="http://website.com/folder/file.html">link</a>
```suggestion
    <a href="http://example.com/folder/file.html">link</a>
```

2021-11-15 01:59 UTC, sibiraj-s commented on tests/cli.spec.js
> +  // TODO: Temp fix for CI running on node 12, since
done.

2021-11-15 01:59 UTC, sibiraj-s commented on tests/cli.spec.js
> +  // since fs.rm is available only since node 14
done

2021-11-15 01:59 UTC, sibiraj-s commented on tests/fixtures/url.html
> +  <form action="http://website.com/folder/folder2/index.html">
done.

2021-11-15 02:00 UTC, sibiraj-s commented on tests/fixtures/url.html
> +  <link rel="stylesheet" href="http://website.com/style.css">
done

2021-11-15 02:00 UTC, sibiraj-s commented on tests/fixtures/url.html
> +    <a href="http://website.com/folder/file.html">link</a>
done

2021-11-19 09:20 UTC, sibiraj-s commented
Lets merge this?

2021-11-21 11:07 UTC, DanielRuf approved these changes

2021-11-21 13:10 UTC, merged